### ISSUE TITLE
Indent multiple lines based on selection

### ISSUE THREAD

**Issue by MadLittleMods** [kazzkiq/CodeFlask.js#12]
Make tab indention([and unindent](https://github.com/kazzkiq/CodeFlask.js/issues/11)) work when you have multiple lines of text selected.

So if you have three lines selected, each line should be indented when pressing `tab`.

**Comment by kazzkiq** [comment]
CodeFlask uses a `textarea` element to write code. As far as I know, it is impossible to implement multiple cursors in form elements, and this would bring a whole new level of refactoring to the library.

For now, CodeFlask is intended to me just a "micro code-editor", and thus would not need this advanced feature. This may change in the (far) future.

**Comment by MadLittleMods** [comment]
@kazzkiq The feature request is afer multi-line indenting, not multiple cursors. You can check out a [demo of multi-line indention here](http://jsfiddle.net/MadLittleMods/U4uJh/) that uses https://github.com/wjbryant/taboverride

**Comment by kazzkiq** [comment]
Hmm, totally misunderstood the request. 😄 

In this case, I'm reopening it, but not sure when I will be able to take a look at it.

**Comment by ivanalemunioz** [comment]
#42 resolve this issue
