### ISSUE TITLE
Missing newlines without JavaScript enabled

### ISSUE THREAD

**Issue by joesavage** [kazzkiq/CodeFlask.js#14]
Without JavaScript enabled, the code snippets are fairly unreadable. Screenshot attached.

![screenshot](https://cloud.githubusercontent.com/assets/1154110/13648996/66ab9d40-e633-11e5-9497-47d494a3b676.png)

**Comment by kazzkiq** [comment]
As CodeFlask can run on any element and is set programmatically, there is no "easy way" to determine when a element will turn into a code editor without JavaScript.

That being said, I think there should be a CSS class such as `.CodeFlask__is-code` that would make the code a little more readable in case JavaScript doesn't run. But this class would have to be added manually on the desired element.

**Comment by michaspiss** [comment]
A simple solution would be to add white-space: pre; to the .code-editor class (.code-window .code-editor in the css file). This way the line breaks will be shown even when JavaScript is disabled.

![codeflask js simple code editor for awesome web pages](https://cloud.githubusercontent.com/assets/17252710/18416665/dd987c60-781a-11e6-9916-4fc0458ca6bd.png)

**Comment by kazzkiq** [comment]
Fixed by #21
