### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by joesavage** [kazzkiq/CodeFlask.js#15]
From `bower.json`it seems that the project is under the MIT license, but this isn't made particularly clear.

**Comment by kazzkiq** [comment]
CodeFlask.js is under MIT license as well as [Prism.js](https://github.com/PrismJS/prism/blob/gh-pages/LICENSE) (library that powers CodeFlask.js syntax highlight)

Just added a LICENSE file to prevent dubiety.
