### ISSUE TITLE
why get such an error?

### ISSUE THREAD

**Issue by zhangkaka** [kazzkiq/CodeFlask.js#19]
<head>
    <meta charset="UTF-8">
      <link rel="stylesheet" href='/static/js/bower_components/prism/themes/prism.css'>
      <link rel="stylesheet" href='/static/js/bower_components/codeflask.js/src/codeflask.css'>
    <script src="/static/js/bower_components/prism/prism.js" async></script>
    <script src="/static/js/bower_components/codeflask.js/src/codeflask.js" async></script>
    <title>Title</title>
</head>

<body>

  <div id="my-code-wrapper" data-language="javascript"></div>

  <script>
    var flask = new CodeFlask;
    flask.run('#my-code-wrapper', { language: 'javascript' })
  </script>
</body>
# 

Uncaught ReferenceError: CodeFlask is not defined

**Comment by kazzkiq** [comment]
Is there any image? Are you making sure to start CodeFlask only after the script is imported?

Try this:

```js
window.onload = function() {
    //... your CodeFlask code inside here
    // will only run when page is fully loaded
}
```

**Comment by phoenixweiss** [comment]
I have the same error, but nothing works.

**Comment by gewaking** [comment]
Same error message:
```
typeError: CodeFlask is not a constructor
var flask = new CodeFlask;
```

Using exactly the same code as in demo

```
window.onload = function() {
  var flask = new CodeFlask;
    flask.run('.code-editor');
}
```

**Comment by AndreYonadam** [comment]
Yes the following code that @kazzkiq has posted does work which I tested since I was able to recreate the issue:
```javascript
window.onload = function() {
     //... your CodeFlask code inside here
     // will only run when page is fully loaded
}
```

Also in addition to that if you get an error saying... 

> TypeError: undefined is not an object (evaluating 'opts.enableAutocorrect')

that means you have to change your javascript to include the code type like this:
```javascript
flask.run('#my-code-wrapper', {
	    language: 'js'
});
```
