### ISSUE TITLE
Support right-to-left languages

### ISSUE THREAD

**Issue by MajidCS** [kazzkiq/CodeFlask.js#26]
Hi,

this project is cool and i want use it. but it does not support RTL language. could you pleas consider adding this feature?

For example : [Bi-directional Text Demo](https://rawgit.com/cben/CodeMirror/37a71a50360a7379e3b1ac55768b96ae8c357feb/demo/bidi.html)

Thanks a lot

**Comment by AndreYonadam** [comment]
Interesting. I got somewhere but right clicking on the textfield and clicking the following to change the direction of the writing. This was in Chrome.
![image](https://cloud.githubusercontent.com/assets/4000593/21874052/28f51dc6-d838-11e6-8e1d-e390f4bd7d40.png)


However the overlay was still doing left to right so I'm assuming there is a way to do that also using CSS.
![image](https://cloud.githubusercontent.com/assets/4000593/21874217/4f639b94-d839-11e6-9a87-c61dde091837.png)

**Comment by AndreYonadam** [comment]
How's it going @MajidCS . What are the symptoms you are exhibiting when using RTL other than the overlay is not on the correct side?

**Comment by AndreYonadam** [comment]
I think I might know the first for this. I will probably get to it sometime in the next few days.

**Comment by AndreYonadam** [comment]
Just as a heads up. Safari also has a feature that allows setting the text direction as shown below.
![image](https://cloud.githubusercontent.com/assets/4000593/21951684/fafed968-d9cf-11e6-975f-009a2c50ff36.png)

If you want to change the direction to RTL I've found that all you have to do is add a direction property with rtl as the css value to the container that holds both the textarea and the span elements.

**Comment by kazzkiq** [comment]
A quick `text-align: right` on `.CodeFlask__textarea` and `.CodeFlask__code` should do most of the job.

The problem is that indentation should also get handled properly on RTL mode (which means there would be changes on JS as well as CSS). I believe this should be added as an option to `.run()`/`.runAll()` functions. Something like:

```javascript
const flask = new CodeFlask;
flask.run('#editor', {language: 'javascript', rtl: true}) // add rlt functionality
```

**Comment by AndreYonadam** [comment]
@kazzkiq  That's what I was mentioning too. I might be able to write something up that includes both allowing people to select the RTL mode on runtime when running the editor and also some JS code that listens to the changes to the textarea text-align css property that changes the placeholder one as well.

**Comment by kazzkiq** [comment]
@AndreYonadam awesome! Once you move forward with the code, or if you get in any trouble, please let us know.

**Comment by AndreYonadam** [comment]
Pull request #28 fixes all these features just as described.

**Comment by AndreYonadam** [comment]
@MajidCS  Sure thing. I've been working on it but it seems that it's not producing an idea result. I'm not really familiar with how it's supposed to work but it seems like it's a limitation for all textareas when in RTL mode. Check the gif @kazzkiq has posted in #28 . We're getting mis-formatting for some reason.

**Comment by MajidCS** [comment]
We need this mostly with Markdown

[it's working](http://i.imgur.com/Ld2DPuz.gifv)

**Comment by AndreYonadam** [comment]
@MajidCS Wow thanks for the testing. I wasn't able to test it because I didn't know what the expected output was. Thanks again.

**Comment by kazzkiq** [comment]
PR #28 fixes this.
