### ISSUE TITLE
I can't use prism 1.6.0 because BOWEL want to use 1.0.1 version only.

### ISSUE THREAD

**Issue by SergeyKhodussov** [kazzkiq/CodeFlask.js#29]
Could you fix bower.json? I can't use prism 1.6.0 because BOWEL want to use 1.0.1 version only:

**bower - ECONFLICT Unable to find suitable version for prism**

```
"dependencies": {
    "prism": "~1.0.1"
  },
```

**Comment by AndreYonadam** [comment]
I think the bower.json file should use `resolutions`.

**Comment by AndreYonadam** [comment]
Can you actually try to use this instead in the json file:
https://gist.github.com/AndreYonadam/1ef8a93ee4dbfd922083e1d59ff88260

**Comment by SergeyKhodussov** [comment]
I think you should set required version like this:

```
  "dependencies": {
    "jquery": ">=1.7.1"
  },
```
for example - https://github.com/uxsolutions/bootstrap-datepicker/blob/master/bower.json

**Comment by SergeyKhodussov** [comment]
Nevertheless, I tried your option - did not help.

**Comment by AndreYonadam** [comment]
Interesting. I think @kazzkiq might be able to help out here since I'm not that used to BOWEL. I tried Google'ing the issue and there are quite a lot of results, just not about "prism" specifically.

**Comment by SergeyKhodussov** [comment]
I tried to use this variation and it helped me:

```
{
  "name": "codeflask.js",
  "version": "0.2.0",
  "homepage": "http://kazzkiq.github.io/CodeFlask.js/",
  "repository": {
    "type": "git",
    "url": "git://github.com/kazzkiq/CodeFlask.js"
  },
  "authors": [
    "Claudio Holanda"
  ],
  **"dependencies": {
    "prism": ">=1.0.1"
  },**
  "description": "A micro code-editor for awesome web pages.",
  "main": [
    "src/codeflask.js",
    "src/codeflask.css"
  ],
  "keywords": [
    "code-editor",
    "plugin",
    "syntax-highlight"
  ],
  "license": "MIT",
  "ignore": [
    "**/.*",
    "node_modules",
    "bower_components",
    "test",
    "tests"
  ],
  "_release": "0.2.0",
  "_resolution": {
    "type": "version",
    "tag": "v0.2.0",
    "commit": "38ca9fb047d047a8ccbec78908057f11249d851e"
  },
  "_source": "https://github.com/kazzkiq/CodeFlask.js.git",
  "_target": "0.2.0",
  "_originalSource": "codeflask"
}
```

**Comment by AndreYonadam** [comment]
@SergeyKhodussov Thanks for sharing that. I'm sure someone else can make use of it!
