### ISSUE TITLE
Exposing code in CodeFlask API

### ISSUE THREAD

**Issue by kazzkiq** [kazzkiq/CodeFlask.js#33]
CodeFlask should have a method for exposing the current code inside the editor.

Something like:

```js
const flask = new CodeFlask;
flask.run('#my-editor');

flask.code(); // Retrieve current code in the editor.
```

**Comment by marcelodarroyo** [comment]
It is very simple:

CodeFlask.prototype.getCode = function () {
    return this.textarea.value;
}

**Comment by kazzkiq** [comment]
This is now done in **1.0**.
