### ISSUE TITLE
Wrong main field in package.json

### ISSUE THREAD

**Issue by lehni** [kazzkiq/CodeFlask.js#43]
I've been trying to use codeflask from webpack, and I am getting the following error:

```
Module not found: Error: Can't resolve 'codeflask'
```

I discovered this is because inside `package.json`, the `main` field points to the non-existing `index.js`:

```json
"main": "index.js",
```
I've manually changed it to this, and the import works:

```json
"main": "src/codeflask.js",
```

It's almost too simple a fix for a PR, but I could create one if desired.

**Comment by piranna** [comment]
> It's almost too simple a fix for a PR, but I could create one if desired.

No pull-request is simple enough to don't do it, some are just typos on the readme and this is fairly more important, so go for it ;-)

**Comment by lehni** [comment]
Oh wait, this isn't actually enough to fix it. It also needs AMD / CommonJS & co. logic for this to correctly work. I will create a proper PR.
