### ISSUE TITLE
Load code from file

### ISSUE THREAD

**Issue by nunos7** [kazzkiq/CodeFlask.js#48]
Hi, It's possible to load code from file using jquery and then run codeflask to edit that code?
Example here: [http://plnkr.co/edit/lwy2Zk11UJ8GVWX1JgKD?p=preview](url)

In the example the html code is rendered as HTML...

NS

**Comment by kyleknighted** [comment]
You could try out some AJAX. This appears to work.

```
$(document).ready(function() {
  var flask = new CodeFlask();
  
  $.get('code.html', function(data) {
    console.log(data);
    flask.run('#my-code-wrapper', { language: 'html' });
    flask.update(data);
  })
});
```
