### ISSUE TITLE
Deprecated or No Longer Supported?

### ISSUE THREAD

**Issue by kyleknighted** [kazzkiq/CodeFlask.js#50]
Noticed PRs seem to be multiple months old.
Has the maintainer stopped supporting this plugin?
Has it been deprecated in favor of other plugins?

**Comment by kazzkiq** [comment]
Hi @kyleknighted,

I've been *extremely* absent from my projects for some time now, only being able to do some minor contributions to OS projects (including my own). But CodeFlask **is definitely not** deprecated nor unsupported.

I'm planning to make this version more stable by fixing major bugs, so I can work on a newer version using `contenteditable`, which I believe will not only help with performance, but will also prevent odd UI bugs such as the ones in #47, #34, etc.
