### ISSUE TITLE
Add support for auto closing certain characters

### ISSUE THREAD

**Issue by VojtechKlos** [kazzkiq/CodeFlask.js#51]
Hello, is there a possibility you could add support for autoclosing certain characters like brackets and quotes? e.g. when editing a json you can just type one `{` and the editor would automatically write a closing `}`

Thanks for reply and keep up the good work. ;-)

**Comment by kazzkiq** [comment]
This is now added in **1.0**.

Characters such as: `[]`, `()`, `{}` and `<>` close themselves automatically.
