### ISSUE TITLE
How to use the code from the editor?

### ISSUE THREAD

**Issue by lepel100** [kazzkiq/CodeFlask.js#53]
Hello,

Is this a toy for the user, or something that's just there for aesthetics? Because it seems
impossible to actually use the code inside the editor. 

In my use case I have 2 editors that and the code inside needs to be send to the server and processed, how can I achive that with this script, if possible by default.

**Comment by lepel100** [comment]
update: I did implement this feature now, by adding a getCode function. If you're interested let me know..

**Comment by kazzkiq** [comment]
You're right. Right now the only way to get the code is using `.onUpdate()` or adding a `value-changed` event listener. There should be a way to do that without events fired.

Glad to know you actually solved it. Do you mind linking the code with the solution? Or perhaps opening a PR?

**Comment by kazzkiq** [comment]
This is implemented in **1.0**.
