### ISSUE TITLE
Release new version?

### ISSUE THREAD

**Issue by marcosnils** [kazzkiq/CodeFlask.js#54]
I see that line-numbers support is not available in any release yet. Any plans to make a new release with that feature?

**Comment by subversivo58** [comment]
Described in te README.md

> To output the line numbers you would also need the [Line Numbers](http://prismjs.com/plugins/line-numbers/) plugin.

Line Numbers is Prisma plugin, Prisma is optional for use this library to display "sintax-highlighted" code.

[Prisma](http://prismjs.com/)
[Line Numbers](http://prismjs.com/plugins/line-numbers/) (prisma plugin)

**Comment by kazzkiq** [comment]
In version **1.0** `lineNumbers` are working properly.

If you really need to stick with the legacy (`0.x`) version, I recomend updating your package to `0.3.1`.
