### ISSUE TITLE
Create Bower package

### ISSUE THREAD

**Issue by kazzkiq** [kazzkiq/CodeFlask.js#9]
CodeFlask.js have dependency on Prism.js. I don't know how the dependency policy works on Bower, but we would need to import Prism too.

Related to PullRequest #7 .

**Comment by pleasedontbelong** [comment]
done. I've also modified the README file. Don't forget to register your code it in bower n_n

**Comment by princed** [comment]
Please, please publish to npm as well!

**Comment by kazzkiq** [comment]
Package registered. Now you can import CodeFlask.js by using:

```bash
bower install codeflask
```
